import { test } from 'node:test';
import assert from 'node:assert/strict';
import { account, client, otp } from './helpers.mjs';
test('running Docker: verified Owner creation, isolation and recovery', async () => {
  const { request, email, password } = await account('owner');
  assert.equal((await request('/api/businesses', {name: 'Unverified'})).status, 401);
  assert.equal((await request('/api/auth/sign-in/email', {email,password})).status, 403);
  const token = await otp(email, 'email-verification');
  assert.equal((await request('/api/auth/email-otp/verify-email', {email,otp:'invalid'})).status, 400);
  assert.equal((await request('/api/auth/email-otp/verify-email', {email,otp:token})).status, 200);
  assert.equal((await request('/api/auth/email-otp/verify-email', {email,otp:token})).status, 400);
  assert.equal((await request('/api/auth/sign-in/email', {email,password})).status, 200);
  const created = await request('/api/businesses', {name:'Durable Business'});
  assert.equal(created.status, 201);
  assert.equal(created.data.role, 'Owner');
  const business = created.data;
  assert.equal((await request('/api/businesses', {name:'Forged',ownerId:'someone'})).status, 400);
  assert.equal((await request('/api/businesses', {name:'Bad origin'}, {headers:{origin:'https://evil.test'}})).status, 403);
  assert.equal((await request('/api/businesses', {name:'Missing origin'}, {headers:{origin:null}})).status, 403);
  assert.equal((await request('/api/auth/sign-out', {}, {headers:{origin:'https://evil.test'}})).status,403);
  assert.equal((await request('/api/businesses', {name:''})).status,400);
  assert.equal((await request('/api/businesses', {name:'x'.repeat(121)})).status,400);
  assert.equal((await request('/api/businesses', {name:'Content type'}, {headers:{'content-type':'text/plain'}})).status,415);
  assert.equal((await request('/api/businesses/'+ '-'.repeat(36))).status,404);
  const stranger = await client();
  assert.equal((await stranger('/api/businesses', {name:'Anonymous'})).status, 401);
  assert.equal((await stranger(`/api/businesses/${business.id}`)).status, 401);
  const other = await account('other');
  assert.equal((await other.request('/api/auth/email-otp/verify-email', {email:other.email,otp:await otp(other.email,'email-verification')})).status,200);
  const otherLogin=await other.request('/api/auth/sign-in/email', {email:other.email,password:other.password});
  assert.equal(otherLogin.status,200,JSON.stringify(otherLogin.data));
  assert.equal((await other.request(`/api/businesses/${business.id}`)).status, 404);
  assert.deepEqual((await other.request('/api/businesses')).data, []);
  assert.equal((await request('/api/auth/email-otp/request-password-reset', {email})).status, 200);
  const reset = await otp(email, 'forget-password');
  assert.equal((await request('/api/auth/email-otp/reset-password', {email,otp:'invalid',password:'Replacement-938!'})).status, 400);
  assert.equal((await request('/api/auth/email-otp/reset-password', {email,otp:reset,password:'Replacement-938!'})).status, 200);
  assert.equal((await request('/api/auth/email-otp/reset-password', {email,otp:reset,password:'Replacement-938!'})).status, 400);
  assert.equal((await request('/api/businesses')).status, 401);
  assert.equal((await request('/api/auth/sign-in/email', {email,password})).status, 401);
  assert.equal((await request('/api/auth/sign-in/email', {email,password:'Replacement-938!'})).status, 200);
  assert.equal((await request(`/api/businesses/${business.id}`)).data.name, 'Durable Business');
  const unicode=Buffer.from(JSON.stringify({name:'Café'}));
  const split=unicode.indexOf(0xc3)+1;
  const streamed=await request('/api/businesses',{}, {chunks:[unicode.subarray(0,split),unicode.subarray(split)]});
  assert.equal(streamed.status,201);
  assert.equal(streamed.data.name,'Café');
  assert.equal((await request('/api/businesses/'+streamed.data.id)).data.name,'Café');
  assert.equal((await request('/health/ready')).status, 200);
});
